# Generated by Django 3.2.5 on 2021-08-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0002_appointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_pk',
        ),
    ]
